### ISSUE TITLE
Demo Workflow

### ISSUE THREAD

**Issue by ipapandinas** [kudos-ink/demo#3]
## Abstract

This contract triggers `Demo` Smart Contract.
Support the `Workflow` trait interface described in #1 .

**Comment by leapalazzolo** [comment]
It would be great if we could use the current issue (https://github.com/kudos-ink/demo/issues/**3**) number instead of the global issue ID (we used it in the hackathon demo).

**Comment by ipapandinas** [comment]
Yes, we can use the `github` context's `issue.number` property to get the number of the issue that triggered the workflow:

```
run: echo "The issue number is ${{ github.event.issue.number }}"
```
